# Generated by Django 4.1.5 on 2023-01-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payhereuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
