# Generated by Django 4.1.5 on 2023-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_admin_payhereuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhereuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='payhereuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
