# Generated by Django 4.1.5 on 2023-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
